[package]
name = "web"
version = "0.1.0"
edition = "2021"
default-run = "web"

[lib]
name = "web"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.48.0", features = ["net", "io-util", "rt", "macros", "rt-multi-thread"] }

